### GET All items
GET http://localhost:3000/items HTTP/1.1

### GET Single item
GET http://localhost:3000/items/5 HTTP/1.1

### POST Item
POST http://localhost:3000/items HTTP/1.1
Content-Type: application/json

{
  "name": "New Item"
}

### DELETE Item
DELETE http://localhost:3000/items/2 HTTP/1.1

### UPDATE Item
PUT http://localhost:3000/items/1 HTTP/1.1
Content-Type: application/json

{
  "name": "Updated item"
}